language: cpp
compiler: 
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install qt-sdk
script:
  - mkdir build
  - cd build
  - qmake ../flyelephant.pro
  - make -f Makefile.Debug
